### ISSUE TITLE
Program gets  "Error Setting up PI Engineering Device", crashes if I do anything after that.

### ISSUE THREAD

**Issue by rec** [piengineering/xkeys#1]
I built as per the instructions without incident, and attempted to run the demo program `build/testgui/pietestgui`.  I see a GUI window, but when I click start, I get:

    `Error Setting up PI Engineering Device`

and then the program crashes if I try to actually do anything.

I instrumented the program a little and discovered that the error code (which the programmer didn't take the time to put in the error message) is 205:  `PIE_HID_SETUP_CANNOT_OPEN_READ_HANDLE` and the path that it's trying to open at that point is `0003:0010:00` (whatever that means).

Here's what's printed on the console.

    Continuing, vid: 2222 pivid: 5f3
    Continuing, vid: 2222 pivid: 5f3
    Continuing, vid: 2222 pivid: 5f3
    Found XKeys Device:
        PID: 0405
        Usage Page: 000c
        Usage:      0001
        Version: 256

    Found XKeys Device:
        PID: 0405
        Usage Page: 0001
        Usage:      0006
        Version: 256

    Found XKeys Device:
        PID: 0405
        Usage Page: 0001
        Usage:      0002
        Version: 256

**Comment by jgarvin** [comment]
Can confirm, seeing the same issue.

**Comment by ambermccormick** [comment]
Hello, jgarvin. Because this problem does not exist across the board (did not/does not exist on our test machines), we need a bit more information to chase down the issue. Which distro are you seeing this behavior on?

**Comment by jgarvin** [comment]
I actually figured it out. The problem is just that I hadn't copy the udev file over, so my username didn't permission to access the file for the pedals. You might want to add a FAQ entry to your README or change the program itself to suggest checking this in the error message.

While I have your attention though -- is there anyway using the bundled programs in the SDK to map the pedals to key presses, or do I need to write code myself using the API to accomplish that? (I'm on Linux)

**Comment by ambermccormick** [comment]
jgarvin, thank you for the follow-up. It sounded like a permissions issue to me too, but I wasn't sure the culprit. I will add it to the list of updates.

The SDK doesn't included any sample code for key presses, but when I was testing originally I used this sample as a reference to send keystrokes: http://www.doctort.org/adam/nerd-notes/x11-fake-keypress-event.html
